name: "zeta-guard"

services:
  keycloak:
    environment:
      KC_FEATURE_OPENTELEMETRY_LOGS: enabled
      KC_TELEMETRY_ENDPOINT: http://lgtm:4318
      KC_TELEMETRY_PROTOCOL: http/protobuf
      KC_TELEMETRY_LOGS_ENABLED: true
      KC_TRACING_ENABLED: true

  opa:
    command:
      - run
      - --server
      - --log-level=info
      - --addr=0.0.0.0:8181
      - --diagnostic-addr=0.0.0.0:8282
      - --set
      - decision_logs.console=true
      - --set
      - distributed_tracing.address=http://lgtm:4318
      - --set
      - distributed_tracing.type=grpc
      - /bundle

  lgtm:
    # an OpenTelemetry backend, see https://grafana.com/docs/opentelemetry/docker-lgtm/
    image: grafana/otel-lgtm
    networks:
      - zeta-guard
    ports:
      - "13000:3000"  # Grafana (http://localhost:13000). User: admin, password: admin
      - "14317:4317"  # OpenTelemetry GRPC endpoint
      - "14318:4318"  # OpenTelemetry HTTP endpoint
