/*-
 * #%L
 * keycloak-zeta
 * %%
 * (C) tech@Spree GmbH, 2026, licensed for gematik GmbH
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * *******
 *
 * For additional notes and disclaimer from gematik and in case of changes by gematik find details in the "Readme" file.
 * #L%
 */
package de.gematik.zeta.zetaguard.keycloak.plugins.hsmproxy

import de.gematik.zetaguard.hsmproxy.HsmProxyProvider
import java.io.ByteArrayOutputStream
import java.security.KeyStore
import java.security.Security
import java.util.Properties
import org.keycloak.Config
import org.keycloak.events.EventListenerProviderFactory
import org.keycloak.models.KeycloakSession
import org.keycloak.models.KeycloakSessionFactory
import org.slf4j.LoggerFactory

private val log = LoggerFactory.getLogger(HsmProxyKeycloakFactory::class.java)

/** Alias used in the HSMPROXY KeyStore — matches `keys.tls.*` config properties. */
private const val KEY_ALIAS = "tls"

/** ENV var: gRPC endpoint of the HSM Proxy (e.g. `hsm-proxy:50051`). */
const val ENV_HSM_PROXY_ENDPOINT = "HSM_PROXY_ENDPOINT"

/** ENV var: key ID in the HSM (e.g. `zeta-guard-keycloak-tls-es256-v1.p256`). */
const val ENV_HSM_PROXY_KEY_ID = "HSM_PROXY_KEY_ID"

/**
 * Keycloak plugin that warms up the HSM connection at startup and proves it is reachable.
 *
 * Uses the [EventListenerProviderFactory] SPI as a startup hook — the event listener itself is a no-op.
 * All initialisation happens in [postInit], which is called once after all Keycloak factories are ready.
 *
 * ## Configuration (environment variables)
 *
 * | Variable | Example | Description |
 * |---|---|---|
 * | `HSM_PROXY_ENDPOINT` | `hsm-proxy:50051` | gRPC endpoint of the HSM Proxy |
 * | `HSM_PROXY_KEY_ID` | `zeta-guard-keycloak-tls-es256-v1.p256` | Key ID in the HSM |
 *
 * The plugin is **opt-in**: if both variables are set the warm-up runs; if either is absent the
 * plugin logs a warning and remains inactive. This allows running Keycloak without an HSM (e.g.
 * local development, HTTP-only setups).
 *
 * ## TLS wiring
 *
 * [HsmProxyProvider] is registered at JVM startup via `security.provider.14` in the baked-in
 * `java.security` file — before Quarkus TLS initialisation runs. [postInit] also calls
 * [Security.addProvider] as a defensive fallback for images built before that entry was added
 * (it is a no-op if the provider is already registered).
 *
 * To make Keycloak use the HSM key for TLS, configure:
 * ```
 * KC_HTTPS_KEY_STORE_TYPE=HSMPROXY
 * KC_HTTPS_KEY_STORE_FILE=/opt/keycloak/conf/hsm-keystore.properties   # generated by startup.sh from HSM_PROXY_* env vars
 * KC_HTTPS_KEY_STORE_ALIAS=tls
 * ```
 */
open class HsmProxyKeycloakFactory : EventListenerProviderFactory {

  override fun getId() = "zeta-hsm-proxy"

  override fun init(config: Config.Scope) {
    // Config is read in postInit via System.getenv — no-op here.
  }

  override fun postInit(factory: KeycloakSessionFactory) {
    val endpoint = getenv(ENV_HSM_PROXY_ENDPOINT)
    val keyId = getenv(ENV_HSM_PROXY_KEY_ID)

    if (endpoint == null || keyId == null) {
      log.warn(
        "🔐 HsmProxyProvider disabled — set {} and {} to enable HSM-backed TLS",
        ENV_HSM_PROXY_ENDPOINT,
        ENV_HSM_PROXY_KEY_ID,
      )
      return
    }

    // Defensive registration: no-op if already registered via security.provider.14 in java.security.
    // Required for images built before that entry existed, and for the warm-up call below.
    Security.addProvider(HsmProxyProvider())

    log.info("🔐 Loading HSMPROXY KeyStore (endpoint={}, keyId={})", endpoint, keyId)
    buildKeyStore(endpoint, keyId)

    log.info("🔐 HSMPROXY KeyStore loaded successfully — HSM gRPC channel is reachable")
  }

  override fun create(session: KeycloakSession) = HsmProxyKeycloakProvider()

  override fun close() = Unit

  // open for testing — allows subclasses to override KeyStore loading
  protected open fun buildKeyStore(endpoint: String, keyId: String): KeyStore {
    val props =
      Properties().apply {
        setProperty("hsm.endpoint", endpoint)
        setProperty("keys.$KEY_ALIAS.key_id", keyId)
      }
    val baos = ByteArrayOutputStream()
    props.store(baos, null)
    return KeyStore.getInstance(HsmProxyProvider.KEYSTORE_TYPE).also {
      it.load(baos.toByteArray().inputStream(), null)
    }
  }

  // open for testing — allows subclasses to override env var lookup without mocking System
  protected open fun getenv(name: String): String? = System.getenv(name)
}
