POST {{origin}}/realms/zeta-guard/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=urn:ietf:params:oauth:grant-type:token-exchange&
client_id=zeta-client&
subject_token={{someAccessToken}}&
subject_token_type=urn:ietf:params:oauth:token-type:jwt&
scope=audience-target-scope&
requested_token_type=urn:ietf:params:oauth:token-type:access_token&
client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&
client_assertion=client-jwt

#audience=audience-target-client
# Hard-coded token for testing
# subject_token={{someAccessToken}}&
